
FROM ollama/ollama:latest


RUN ollama pull gpt-20b


COPY ollama-prompt.txt /app/ollama-prompt.txt
# If you have a functions file, uncomment the next line
# COPY functions.json /app/functions.json


ENV OLLAMA_SYSTEM_PROMPT_FILE=/app/ollama-prompt.txt
# If you have a functions file, uncomment:
# ENV OLLAMA_FUNCTIONS_FILE=/app/functions.json


EXPOSE 11434


CMD ["ollama", "serve"]
